{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <test_pytest.test_pytest.TestClass object at 0x0000023748A67888>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, \"check\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_pytest\\test_pytest.py:43: AssertionError"}, "start": 1583051668813, "stop": 1583051668813, "uuid": "1bd2e0f9-dfbd-4266-a2b0-90c51d82c9b2", "historyId": "1a3b91e14faa07dcdcb8b7ae9ff35c83", "testCaseId": "2814cd1496d73dd219c414a328e4e062", "fullName": "test_pytest.test_pytest.TestClass#test_two", "labels": [{"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "luoluo-PC"}, {"name": "thread", "value": "3032-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.test_pytest"}]}